# Generated by Django 5.1.4 on 2025-01-11 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aseguradora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('tax_id', models.CharField(max_length=100)),
                ('activo', models.CharField(choices=[('S', 'Sí'), ('N', 'No')], default='S', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Matriz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('activo', models.CharField(choices=[('S', 'Sí'), ('N', 'No')], default='S', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='logos/')),
                ('pais', models.CharField(max_length=100)),
                ('domicilio_oficina', models.CharField(max_length=100)),
                ('url_web', models.CharField(max_length=100)),
                ('activo', models.CharField(choices=[('S', 'Sí'), ('N', 'No')], default='S', max_length=3)),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.matriz')),
            ],
        ),
    ]
