# Generated by Django 5.1.4 on 2025-01-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_aseguradora_pais_alter_broker_pais_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aseguradora',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='matriz',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pais',
            name='codigo',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
