# Generated by Django 5.1.4 on 2025-01-15 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_matriz_modified_by_pendingchange'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingchange',
            name='submitted_at',
        ),
        migrations.AddField(
            model_name='pendingchange',
            name='action_type',
            field=models.CharField(choices=[('edit', 'Edición'), ('delete', 'Eliminación')], default='edit', max_length=10),
        ),
        migrations.AlterField(
            model_name='pendingchange',
            name='approved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pendingchange',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
