# Generated by Django 5.1.4 on 2025-01-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_pendingchange_submitted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingchange',
            name='approved',
            field=models.BooleanField(null=True),
        ),
    ]
